# Generated by Django 4.1.1 on 2023-04-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('offers', '0002_offers_location_offers_ulr_image'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='offers',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.requests'),
        ),
        
        migrations.AlterField(
            model_name='offers',
            name='body',
            field=models.TextField(max_length=255, verbose_name='Опис'),
        ),
    ]
