# Generated by Django 4.1.1 on 2022-12-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offers_location_offers_ulr_image'),
    ]

    operations = [
        migrations.RenameField('offers', 'ulr_image', 'url_image'),
    ]
